config/routes.rb
BeOneAdmin::Engine.routes.draw do
  root to: "main#index" ,as: :admin_root
  extend BeOneAdmin::RoutableConcern

  %w{sign_in remind}.each do |method|
    post method , to: "sessions##{method}", as: :"admin_#{method}"
  end
  %w{forgot login sign_out }.each do |method|
    get method , to: "sessions##{method}", as: :"admin_#{method}"
  end

  get 'restore/:token' => 'sessions#remind', as: 'remind'

  namespace :uploads do
  end
  namespace :journals do
    resources :logs, only: [:index,:show,:new]
    resources :versions, only: [:index,:show,:new]
  end

  namespace :settings do
    resources :menus do
      patch :move, on: :member
    end
    resources :users, concerns: :habtm_concern
    resources :permissions , concerns: :habtm_concern
    resources :admin_user_groups , concerns: :habtm_concern
    resources :roles , concerns: :habtm_concern
    resources :emails 
    resources :settings 
    resources :notifications , concerns: :has_many_concern
    resources :confirmations , only: [:index]
  end
end

app/models/be_one_admin/application_record.rb
module BeOneAdmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    def presenter
      @presenter ||= "#{self.class.name}Presenter".constantize.new(self)
    end
  end
end

app/models/be_one_admin/confirmation.rb
module BeOneAdmin
  class Confirmation < ApplicationRecord

#    set_primary_keys :user_id, :notification_id

    scope :unread, -> { where read: false }
    belongs_to :notification, foreign_key: :notification_id
    belongs_to :user, foreign_key: :user_id
    delegate :email, to: :user, prefix: true, allow_nil: true

    delegate :heading, to: :notification, prefix: true, allow_nil: true
    delegate :text, to: :notification, prefix: true, allow_nil: true
  end
end

app/models/be_one_admin/email.rb
module BeOneAdmin
  class Email < ApplicationRecord
    multilang :subject, :text
  end
end

app/models/be_one_admin/log.rb
module BeOneAdmin
  class Log 
    def self.column_names
      []
    end
  end
end

app/models/be_one_admin/menu.rb
module BeOneAdmin
  class Menu < ApplicationRecord
    belongs_to :parent, class_name: "BeOneAdmin::Menu", foreign_key: :parent_id, optional: true
    has_many :children, class_name: "BeOneAdmin::Menu", foreign_key: :parent_id

    multilang :title
    is_positionable scope: :parent, start: 1
  end
end

app/models/be_one_admin/notification.rb
module BeOneAdmin
  class Notification < ApplicationRecord
    belongs_to :user, foreign_key: :user_id
    has_many :confirmations, foreign_key: :notification_id
    has_many :users, through: :confirmations
    multilang :text
    multilang :heading
    enum message_type: [:from_user, :bug, :plus, :envelope]
  end
end

app/models/be_one_admin/permission.rb
module BeOneAdmin
  class Permission < ApplicationRecord
    has_and_belongs_to_many :roles, association_foreign_key: :role_id, foreign_key: :permission_id
    has_and_belongs_to_many :users, association_foreign_key: :user_id, foreign_key: :permission_id
    has_many :role_users, through: :roles, source: :users
    multilang :title
  end
end

app/models/be_one_admin/role.rb
module BeOneAdmin
  class Role < ApplicationRecord
    has_and_belongs_to_many :permissions, association_foreign_key: :permission_id, foreign_key: :role_id
    has_and_belongs_to_many :users, association_foreign_key: :user_id, foreign_key: :role_id

    multilang :title
    multilang :description
  end
end

app/models/be_one_admin/user.rb
module BeOneAdmin
  class User < ApplicationRecord
    @use_resource_scoping = true

    has_paper_trail


    options = {
      # default_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Default-avatar.jpg',
      # processors: [:thumbnail, :compression],
      # styles: {list: "100x100>", thumb: "170x170>" },
      # storage: :filesystem,
      # path: ':rails_root/public/system/img/admins/:id/:style.:extension',
      # url: "#{Rails.application.secrets[:app_protocol]}://#{Rails.application.secrets[:app_host]}/system/img/admins/:id/:style.:extension",
    }

    has_one_attached :avatar, options
    has_secure_password
    signinable restrictions: [:ip, :user_agent]

    has_many :notifications
    has_many :confirmations, foreign_key: :user_id
    has_many :received_notifications, through: :confirmations, foreign_key: :notification_id
    has_many :unread_confirmations, -> { unread }, class_name: "BeOneAdmin::Confirmation", foreign_key: :user_id
    has_many :unread_notifications, through: :unread_confirmations, source: :notification


    has_and_belongs_to_many :individual_permissions, association_foreign_key: :permission_id, foreign_key: :user_id, join_table: :admin_permissions_users, class_name: "BeOneAdmin::Permission"
    has_and_belongs_to_many :roles
    has_many :role_permissions, through: :roles, source: :permissions

    belongs_to :accessable, polymorphic: true, optional: true
  end
end

    
    

app/controllers/be_one_admin/application_controller.rb
module BeOneAdmin
  class ApplicationController < ApplicationController

    protect_from_forgery with: :exception
    around_action :set_locale, if: :current_admin
    around_action :set_globals
    before_action :require_login
    after_action :set_csrf_cookie_for_ng
    helper_method :current_admin
    before_action :set_paper_trail_whodunnit



    include BeOneAdmin::ApplicationHelper 

    def not_found
      render layout: 'be_one_admin/404', inline: "",  status: :not_found
    end

    protected

    def set_locale
      cookies[:locale] = current_admin.locale unless I18n.available_locales.include?(cookies[:locale].to_s.to_sym)
      I18n.with_locale(cookies[:locale]) do
        yield
      end
    end

    def require_login
      if current_admin
        RequestStore.store[:resource_scope] = get_resource_scope
      else
        if request.xhr?
          render_as_json( { success: false, message: I18n.t('admin.session_expired'), status: 401 } )
        else
          redirect_to admin_login_path
        end
      end
    end

    def current_admin
      return @current_admin if @current_admin
      RequestStore.store[:journal_parametrizer] = ::BeOneAdmin::Logger
      RequestStore.store[:request_id] = request.env['action_dispatch.request_id']
      RequestStore.store[:request] = request
      RequestStore.store[:user_token] = cookies[:admin_uniq_token]
      @current_admin = BeOneAdmin::UserOperation::Authentificate.new(token: session[:admin_token], ip: request.remote_ip, user_agent: request.user_agent).process if session[:admin_token]
    end

    def set_user_token
      cookies[:admin_uniq_token] = get_new_token unless "#{cookies[:admin_uniq_token]}".first(4) == Time.zone.now.strftime('%d%m')
    end

    def get_new_token
      [Time.zone.now.strftime('%d%m'), 6.times.map{ rand(9) }.join].join
    end

    def set_csrf_cookie_for_ng
      cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
    end

    def verified_request?
      super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN']) || valid_authenticity_token?(session, request.headers['X-XCRF-TOKEN'.downcase])
    end

    def set_globals
      ::Journal.safe_action(params.to_unsafe_h.merge(has_parent: false, args: params.to_unsafe_h.except('controller', 'action'))) do
        set_user_token
        set_app_config
        RequestStore.store[:request_id] = request.env['action_dispatch.request_id']
        RequestStore.store[:request] = request
        RequestStore.store[:user_token] = cookies[:admin_uniq_token]
        if session[:admin_token]
          RequestStore.store[:current_admin] = current_admin
          session.delete(:admin_token) unless !!RequestStore.store[:current_admin]
          raise Exception, "Method is unpermited" if RequestStore.store[:current_admin] && !user_can?(params[:action])
        end
        yield
      end
    end

    def get_resource_scope
      if current_admin.has_root_resource_scope
        {}
      else
        {
          with_children: current_admin.has_child_resource_scope,
          conditions: {
            path: current_admin.path
          }
        }
      end
    end

    def set_app_config
      @app_config = {
        path: BeOneAdmin.config.route
      }
    end

    def user_for_paper_trail
      current_admin.try(:email) || 'Unathorized'
    end

    def info_for_paper_trail
      { ip: request.remote_ip, user_agent: request.user_agent }
    end

  end
end

app/controllers/be_one_admin/journals/logs_controller.rb
module BeOneAdmin
  module Journals
    class LogsController < ApplicationController
      work_with model: "::BeOneAdmin::Log" do 
        actions only: :show
        uncreatable
        set_js_controller "LogsController"
      end


    end
  end
end

app/controllers/be_one_admin/journals/versions_controller.rb
module BeOneAdmin
  module Journals
    class VersionsController < ApplicationController
      work_with model: "::Version" do 
        actions only: :show
        uncreatable
      end

      def _setup_filter_variables
        @available_klasses = ActiveRecord::Base.descendants.map do |klass|
          klass.included_modules.include?(PaperTrail::Model::InstanceMethods) ? klass.name : nil
        end.compact
      end

    end
  end
end

app/controllers/be_one_admin/main_controller.rb
module BeOneAdmin
  class MainController < ::BeOneAdmin::ApplicationController
    def index
      @block_stats = BeOneAdmin::Stat.blocks
    end
  end
end

app/controllers/be_one_admin/sessions_controller.rb
module BeOneAdmin
  class SessionsController < ::BeOneAdmin::ApplicationController
    layout "be_one_admin/login"
    skip_before_action :require_login, only: [:login,:forgot,:restore,:sign_in]

    def login
      if current_admin
        redirect_to :admin_root
      else
        render layout: "be_one_admin/login"
      end
    end

    def sign_in
      process_and_respond!(operation: BeOneAdmin::UserOperation::SignIn.new( request_merge( login_params ) ) ) do |operation, result|
        session[:admin_token] = result
        redirect_to :admin_root  
      end
    end
    def logout
      process_and_respond!(operation: BeOneAdmin::UserOperation::Logout.new( request_merge(  user: current_admin ) ) ) do |operation, result|
        redirect_to :admin_root
      end
    end

    def forgot
      if current_admin
        redirect_to :admin_root
      else
        render layout: "be_one_admin/login"
      end
    end

    def restore
      process_and_respond!(operation: BeOneAdmin::UserOperation::Restore.new( request_merge( restore_params ) ) ) do |operation, result|
        render_as_json( {success: true, message: I18n.t("admin.instructions_was_sended_to_email") } )
      end
    end
    def remind
      process_and_respond!(operation: BeOneAdmin::UserOperation::ResetPassword.new( request_merge(  code: params[:code] ) ) ) do |operation, result|
        flash[:message] = I18n.t("admin.new_password_sended")
        redirect_to :admin_root
      end
    end

    private
    def request_merge _params
      _params.merge(
        token: session[:admin_token], 
        ip: request.remote_ip, 
        referer: request.referer, 
        user_agent: request.user_agent
      )
    end
    def login_params
      params.require(:login).permit(:email,:password)
    end
    def restore_params
      params.require(:login).permit(:email)
    end

  end
end

app/controllers/be_one_admin/settings/emails_controller.rb
module BeOneAdmin
  module Settings
    class EmailsController < ApplicationController
      work_with model: "::BeOneAdmin::Email"
    end
  end
end

app/controllers/be_one_admin/settings/menus_controller.rb
module BeOneAdmin
  module Settings
    class MenusController < ApplicationController
      work_with model: "::BeOneAdmin::Menu" 

      def index
        respond_to do |format|
          format.json do
            process_and_respond!(operation: BeOneAdmin::MenuOperation::Tree.new) do |operation, result|
              render_as_json( { success: true, menu: result } )
            end
          end
          format.html do; render; end
        end
      end

      def move
        process_and_respond!(operation: BeOneAdmin::MenuOperation::Move.new( up: params[:up].present?, id: params[:id] ) ) do |operation, result|
          render_as_json( { success: true } )
        end
      end

    end
  end
end

app/controllers/be_one_admin/settings/permissions_controller.rb
module BeOneAdmin
  module Settings
    class PermissionsController < ApplicationController
      work_with model: "::BeOneAdmin::Permission" do 
        set_js_controller "SettingsPermissionsController"
        set_habtm_relations :roles, :users
        # set_has_many_relations :role_users
      end


      private

      def _prepare_form_data
        {
          modules: BeOneAdmin.modules.keys.map{|k| {id: k,title: k} },
          modulesActions: BeOneAdmin.modules
        }
      end
    end
  end
end

app/controllers/be_one_admin/settings/roles_controller.rb
module BeOneAdmin
  module Settings
    class RolesController < ApplicationController
      work_with model: "::BeOneAdmin::Role" do 
        set_habtm_relations :permissions, :users
      end
    end
  end
end

app/controllers/be_one_admin/settings/settings_controller.rb
module BeOneAdmin
  module Settings
    class SettingsController < ApplicationController
      work_with model: "::Setting"
    end
  end
end

app/controllers/be_one_admin/settings/users_controller.rb
module BeOneAdmin
  module Settings
    class UsersController < ApplicationController
      work_with model: "::BeOneAdmin::User" do 
        set_habtm_relations :individual_permissions, :roles
        has_image :avatar
        actions with: :history
        set_js_controller "User"
      end
      
      def _prepare_form_data
        depots = if current_admin.accessable
          current_admin.accessable.depot.self_and_descendants
        else
          ::Shop::Depot.all
        end
        {
          is_system_owner: current_admin.is_system_owner,
          depots: depots.map{|depot| 
            { 
              id: depot.id, 
              title: depot.title,
              managers: depot.managers.select{|manager| !manager.admin}.map{|manager| {id: manager.id, title: "#{manager.first_name} #{manager.last_name}"}}
            } 
          }
        }
      end
    end
  end
end

app/views/layouts/be_one_admin/404.html.haml
!!!
/[if IE 8] <html lang="en" class="ie8">
/ [if !IE]><!
%html{lang: I18n.locale}
  / <![endif]
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %title=t("#{BeOneAdmin.config.class_name.downcase}.app_title")
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}/
    / ================== BEGIN CSS|JS ==================
    %link{href:"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700", rel: "stylesheet"}/
    = stylesheet_link_tag    "be_one_admin/application", media: "all"
    = javascript_include_tag "be_one_admin/application"
    = csrf_meta_tags
  %body.pace-top
    / begin #page-container
    #page-container
      / begin error
      .error
        .error-code.m-b-10
          404
          %i.fa.fa-warning
        .error-content
          .error-message=t("#{BeOneAdmin.config.class_name.downcase}.404_heading")
          .error-desc.m-b-20
            =t("#{BeOneAdmin.config.class_name.downcase}.404_text").html_safe
          %div
            %a.btn.btn-success{href: root_path}=t("#{BeOneAdmin.config.class_name.downcase}.404_go_back")
      / end error

app/views/layouts/be_one_admin/application.html.haml
!!!
/[if IE 8] <html lang="en" class="ie8">
/ [if !IE]><!
%html{lang: I18n.locale}
  / <![endif]
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %title=title_tag
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}/
    / ================== BEGIN CSS|JS ==================
    %link{href:"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700", rel: "stylesheet"}/
    %script{src: "https://cloud.tinymce.com/5/tinymce.min.js?apiKey=#{BeOneAdmin.config.tiny_mce_key}"}
    = stylesheet_link_tag    "be_one_admin/application", media: "all"
    = javascript_include_tag "be_one_admin/application"
    = javascript_tag("availableLocales = #{I18n.available_locales.to_json}")
    :javascript
       window.appConfig = #{@app_config.to_json.html_safe}
    = csrf_meta_tags
  %body
    / begin #page-container
    #page-container.page-header-fixed.page-sidebar-fixed{ ng_controller: 'MainController',
                                                          ng_class: "{'page-sidebar-minified': minifedSidebar, 'page-sidebar-toggled': !minifedSidebar}"}
      / begin #header
      #header.header.navbar.navbar-default
        / begin container-fluid
        .container-fluid
          / begin mobile sidebar expand / collapse button
          .navbar-header
            %a.navbar-brand{ href: admin_root_path }
              %span.navbar-logo
              =t("admin.app_title_admin")
            %button.navbar-toggle{"data-click"=>"sidebar-toggled", ng_click: "sidebarToogle()", href: "javascript:;"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          / end mobile sidebar expand / collapse button
          / begin header navigation right
          %ul.navbar-nav.navbar-right
            %li.dropdown.navbar-user{ng_class: "{'open': true }"}
              %strong.dropdown-toggle
                %strong="#{I18n.t("admin.uniq_toke_desc")}: #{cookies[:user_token]}"
            - if  current_admin.unread_notifications.any?
              %li.dropdown{ng_class: "{'open': showNotificationMenu }"}
                %a.dropdown-toggle.f-s-14{ng_click: "notificationMenuToogle()", href: "javascript:;"}
                  %i.fa.fa-bell-o
                  %span.label=current_admin.unread_notifications.count

                %ul.dropdown-menu.media-list.pull-right.animated
                  %li.dropdown-header=t("admin.notifications_count", count: current_admin.unread_notifications.count)
                  - current_admin.unread_notifications.limit(5).each do |notification|
                    %li.media{ng_hide: "readedNotifications | contains:#{notification.id}"}
                      %a{ng_click: "showNotification(#{notification.id})"}
                        .media-left

                          %i{class: "fa media-object #{notification_class( notification.message_type )}" }
                        .media-body
                          %h6.media-heading=notification.heading
                          .text-muted.f-s-11=distance_of_time_in_words_to_now( notification.created_at )
                  - if current_admin.unread_notifications.count > 5
                    %li.dropdown-footer.text-center
                      %a{:href => "javascript:;"}=t("admin.view_more")
            %li.dropdown.locales
              %select.form-control{ ng_model: 'locale', ng_change: 'changeLocale()' }
                %option{ ng_repeat: "locale in availableLocales", ng_value: 'locale' }
                  {{locale.toUpperCase()}}
        


            %li.dropdown.navbar-user
              %a.dropdown-toggle{ href: :'javascript:;', data: { toggle: :dropdown } }
                = image_tag current_admin.presenter.foto, alt: "#{current_admin.last_name} #{current_admin.first_name}"
                %span.hidden-xs= "#{current_admin.last_name} #{current_admin.first_name}"
                %b.caret
              .dropdown-menu.dropdown-menu-right
                / %li.arrow
                / %li
                /   = link_to t("admin.edit_profile"), edit_user_path
                / %li
                /   = link_to user_notifications_path do
                /     %span.badge.pull-right{class: current_admin.unread_notifications.count.zero? ? 'badge-primary' : 'badge-danger'}=current_admin.unread_notifications.count
                /     =t("admin.notifications")
                / %li.divider
                = link_to t("admin.log_out"), admin_sign_out_path, class: "dropdown-item"
          / end header navigation right
      / end container-fluid
      / end #header
      / begin #sidebar
      #sidebar.sidebar
        / begin sidebar scrollbar
        %div{ data: { scrollbar: 'left' } }
          / begin sidebar user
          %ul.nav
            %li.nav-profile
              .image
                %a{:href => "javascript:;"}
                  = image_tag current_admin.presenter.foto, alt: "#{current_admin.last_name} #{current_admin.first_name}"
              .info
                = "#{current_admin.last_name} #{current_admin.first_name}"
                %small= current_admin.title
          - cache current_admin do
            = render_menu(current_admin)
      .sidebar-bg
      / end #sidebar
      / begin #content
      #content.content
        = render_breadcrumbs
        / end breadcrumb
        / begin page-header
        %h1.page-header
          = module_header
        / end page-header
        / begin row
        = yield

      / begin scroll to top btn
      %a.btn.btn-icon.btn-circle.btn-success.btn-scroll-to-top.fade{:href => "javascript:;"}
        %i.fa.fa-angle-up
      / end scroll to top btn
    / end page container

app/views/layouts/be_one_admin/login.html.haml
!!!
/[if IE 8] <html lang="en" class="ie8">
/ [if !IE]><!
%html{:lang => "en"}
  / <![endif]
  %head
    =csrf_meta_tags
    =csp_meta_tag
    %meta{:charset => "utf-8"}/
    %title=title_tag
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    = stylesheet_link_tag "be_one_admin/application", media: "all"
  %body
    .login-cover
      .login-cover-image
      .login-cover-bg
    #page-container
      .login.login-v2
        .login-header
          .brand
            %span.logo
            %b=title_tag
            - if login_desc
              %small=login_desc
          .icon
            %i.fa.fa-lock
        .login-content
          = yield